### ISSUE TITLE
是否能发出禁言弹幕?

### ISSUE THREAD

**Issue by vhorng** [xbclub/BilibiliDanmuRobot#28]
有主播问：仅使用直播机(不在直播间)，当管理员禁言某某某时，主播并不知情
有时导致不必要的误会，是否能让主播选择显示"某某某被禁言"的信息？

建议为可选择(可开启或停用)

**Comment by hxhlb** [comment]
PR已提交, 等GUI开发完成就可以发版

**Comment by xbclub** [comment]
已添加
