### ISSUE TITLE
如何在代码里获取到当前登录的机器人的uid

### ISSUE THREAD

**Issue by hqu-little-boy** [xbclub/BilibiliDanmuRobot#35]
``

**Comment by xbclub** [comment]
？？

**Comment by hqu-little-boy** [comment]
我在尝试加入生僻字识别功能，但是机器人会把已经识别的生僻字发送的读音发出的弹幕仍然会被识别，不断的刷屏

**Comment by xbclub** [comment]
https://github.com/xbclub/BilibiliDanmuRobot/blob/master/internal/bullet_girl/robot_bullet.go#L103
参考这个文件的第103行代码获取id
