### ISSUE TITLE
如何设定不欢迎自己？

### ISSUE THREAD

**Issue by vhorng** [xbclub/BilibiliDanmuRobot#41]
不管是主播自己或代挂，当自己进入直播间都会出现 "自己欢迎自己" 的弹幕，看来是不是有点怪!?

已尝试过将自己添加到 "精确匹配"的黑名单，但仍会显示欢迎自己的弹幕

所以想知道这是我设定问题，还是有机会改程式规则？

**Comment by xbclub** [comment]
这个自己指的是主播号还是机器人号

**Comment by vhorng** [comment]
我的问题是机器人号

**Comment by xbclub** [comment]
将在1.3.5版本加入
