### ISSUE TITLE
求解决方案

### ISSUE THREAD

**Issue by Goodjieguo** [xbclub/BilibiliDanmuRobot#5]
![image](https://user-images.githubusercontent.com/53360610/223007878-94dd87f8-5549-4e5c-b5d6-c8ba63f17c5a.png)
![image](https://user-images.githubusercontent.com/53360610/223008365-54b9ba50-fc5a-4d35-b502-23984eeff3fc.png)

**Comment by xbclub** [comment]
openai疑似被某防火墙进行sni阻断和dns污染，建议使用不可描述的方式访问

**Comment by Goodjieguo** [comment]
> 网络问题, 确认你能访问那个网址.

![image](https://user-images.githubusercontent.com/53360610/223379535-c0d4a162-4d72-47eb-85b5-d7f28a3ab7ab.png)

我不知道该怎么做，电脑已开启魔法，可以在网页正常使用ChatGPT，还请教教我~

**Comment by xbclub** [comment]
> > openai疑似被某防火墙进行sni阻断和dns污染，建议使用不可描述的方式访问
> 
> 我不知道该怎么做，电脑已开启魔法，可以在网页正常使用ChatGPT，还请教教我~

请确保你的不可描述行为能被终端使用

**Comment by Goodjieguo** [comment]
> > > openai疑似被某防火墙进行sni阻断和dns污染，建议使用不可描述的方式访问
> > 
> > 
> > 我不知道该怎么做，电脑已开启魔法，可以在网页正常使用ChatGPT，还请教教我~
> 
> 请确保你的不可描述行为能被终端使用

非常感谢，我已成功解决问题
