### ISSUE TITLE
功能问题：关注答谢功能没反应

### ISSUE THREAD

**Issue by vhorng** [xbclub/BilibiliDanmuRobot#55]
在(2024/1/10)有回报过答谢功能没运作，之后有提可能是interactword: true的问题(但我改了也没用)
也提到"关闭入场欢迎就关闭了欢迎答谢"，会在下一版本把这控制独立出来
但在1.3.4版本尚未见到专属控制项，所以在此记录一下

**Comment by xbclub** [comment]
将在1.3.5版本加入
