### ISSUE TITLE
功能问题：欢迎对象用词有缺

### ISSUE THREAD

**Issue by vhorng** [xbclub/BilibiliDanmuRobot#57]
目前的欢迎功能在舰长进入会显示欢迎舰长 某某某
但如果是提督或总督进来，只会显示欢迎 某某某

希望能明确欢迎对象用词
例如：欢迎舰长 某某某，欢迎提督 某某某，欢迎提督 某某某

**Comment by xbclub** [comment]
弹幕接口未做特效与大航海区分
