### ISSUE TITLE
大乱斗尊严票

### ISSUE THREAD

**Issue by vhorng** [xbclub/BilibiliDanmuRobot#62]
大乱斗尊严票：
大乱斗快结束或绝杀时刻被碾压时，送「指定数量」的「指定礼物」
例如：大乱斗快结束或发现快被绝杀时仍为0票，送出10朵人气票

**Comment by hxhlb** [comment]
这功能不会支持.
首先, 如果是主播自己挂机器人, 自己是没法给自己送礼物的.
第二, 如果是别人代挂, 但是他本人又因为囊中羞涩不想开这个功能而又不好意思拒绝主播的要求的时候会很尴尬
第三, 涉及到自动送礼物, 还是带金额的, 这种功能机器人不会操作, 会让用户猜忌到底把礼物送给谁, 会让用户没有安全感.

**Comment by vhorng** [comment]
不开发这功能，没问题~  但还是说一下我的想法
1.的情境我确实忘了主播不能送自己这个规则
但后面两点，应该不是太大的问题
2. 如果主播是这样对待代挂的粉丝，那这主播不支持也罢
3. 这一点只能说我「信任开发者」，且这功能毕竟是选项功能(用户自己决定要不要启用)，不至于送到非代挂的房间吧!?
