### ISSUE TITLE
机器人直播重开无法进入直播间

### ISSUE THREAD

**Issue by user269** [xbclub/BilibiliDanmuRobot#65]
主播重新开播后，机器人只有进入直播间的提示弹幕，无法发送其他的弹幕，只有重新打开才能使用

**Comment by xbclub** [comment]
请提供相关日志

**Comment by user269** [comment]
![屏幕截图 2024-06-29 123228](https://github.com/xbclub/BilibiliDanmuRobot/assets/65118214/b69c7c53-9e48-40ce-900f-d6792a062d57)
![屏幕截图 2024-06-29 123326](https://github.com/xbclub/BilibiliDanmuRobot/assets/65118214/80a08a85-0fcb-454e-bd59-45b177487298)

**Comment by user269** [comment]
其他日志无内容

**Comment by xbclub** [comment]
得看error log

**Comment by user269** [comment]
[error.log](https://github.com/user-attachments/files/16171596/error.log)

**Comment by xbclub** [comment]
v1.3.6 已修复
