### ISSUE TITLE
可以增加一个延迟欢迎的设置吗

### ISSUE THREAD

**Issue by CandW** [xbclub/BilibiliDanmuRobot#72]
很多时候游客压根没进来但是他还是不听的欢迎，希望可以设置检测到进入多久之后入股还在再欢迎。
还有可以设置屏蔽发红包和天选时的关注和欢迎语言。

**Comment by xbclub** [comment]
红包和天选的欢迎会自动避让这是已有的功能，检测多久后的这个功能由于bilibili用户端没有上报用户在线时长的报文咱无法支持
