### ISSUE TITLE
PK相关这个是没有了

### ISSUE THREAD

**Issue by pistachioss** [xbclub/BilibiliDanmuRobot#76]
PK相关
 PK输出对手信息
 对方用户串门识别
 你好，这个是没有了吗， 没看到配置

**Comment by xbclub** [comment]
![屏幕截图 2024-12-22 093044](https://github.com/user-attachments/assets/e01439a9-e4a3-4ba9-938a-d0cd0cdb1009)

**Comment by pistachioss** [comment]
好的
