### ISSUE TITLE
需求：增加黑名单

### ISSUE THREAD

**Issue by GrandMovie** [xbclub/BilibiliDanmuRobot#8]
b站打广告的用户过多，例如小妖网玩、独家朲芞等，需增加可配置黑名单，不欢迎此类用户

**Comment by hxhlb** [comment]
> b站打广告的用户过多，例如小妖网玩、独家朲芞等，需增加可配置黑名单，不欢迎此类用户

功能测试中..

**Comment by hxhlb** [comment]
> 

可以测试一下了
